### PR TITLE
cleaned up warnings and documented a bit

### LINKED ISSUE #54: Cleanup and documentation
Improve the documentation and clean up some clippy warnings

### PR DESCRIPTION
**Pull request by chridou**
closes #54

### CODE REVIEW

**Comment by chridou** [comment]
:+1:

**Comment by panicbit** [comment]
👍

**Comment by panicbit** [comment]
Don't you want to bump the version?

**Comment by chridou** [comment]
Ah, hi! Didn't want to disturb you. There is another PR coming...

**Pull request merged**
